### ISSUE TITLE
Proxy Scaper Repo is Deleted

### ISSUE THREAD

**Issue by zitonDev** [hendrikbgr/Free-Proxy-Repo#1]
Loving the proxies and wanted to check out the scraper itself but it seems like it's been taken down.

**Comment by hendrikbgr** [comment]
Hello, yes I set it private for now - I am working on a public version atm since mine is specifically built to commit and push the found proxies to this repo. Also, it's optimized for the raspberry pi. Once the public version is ready I will announce it on Twitter (@hendrik_bgr)

**Comment by hendrikbgr** [comment]
@zitonDev The Proxy Scraper got updated and can be found here: https://github.com/hendrikbgr/Proxy-Scraper
